const fontStyles = [
  // { fontName: "Catfiles", className: "catfiles" },
  { fontName: "Pervitina", className: "pervitina" },
  { fontName: "Raillinc", className: "raillinc" },
  { fontName: "Campana", className: "campana" },
  { fontName: "EnchantedLand", className: "enchanted-land" },
  // { fontName: "Tac One", className: "tac-one-regular" },
  { fontName: "DevilCandle", className: "devil-candle" },
  { fontName: "Vogue", className: "vogue" },
  { fontName: "Permanent Marker", className: "permanent-marker-regular" },
  { fontName: "Righteous", className: "righteous-regular" },
  { fontName: "Bebas Neue", className: "bebas-neue-regular" },
  { fontName: "adelia", className: "Adelia" },
  { fontName: "Amarillo", className: "Amarillo" },
  { fontName: "Ananda", className: "Ananda" },
  { fontName: "Angelist", className: "Angelist" },
  { fontName: "Anthaya_DEMO", className: "Anthaya" },
  { fontName: "Aston Script", className: "Aston-Script" },
  { fontName: "BillionDreams", className: "BillionDreams" },
  { fontName: "Black Storm", className: "Black-Storm" },
  { fontName: "wolfbones", className: "wolfbones" },
  { fontName: "Cream Cake", className: "Cream-Cake" },
  { fontName: "Aligator", className: "Aligator" },
  { fontName: "Bad Boys", className: "Bad-Boys" },
  { fontName: "Deadknight", className: "Deadknight" },
  { fontName: "Gamerock", className: "Gamerock" },
  { fontName: "Chopsic", className: "Chopsic" },
  { fontName: "Geizer", className: "Geizer" },
  { fontName: "Slaytanic", className: "Slaytanic" },
  { fontName: "DirtyCrown", className: "DirtyCrown" },
  { fontName: "Black Mustang", className: "Black-Mustang" },
  { fontName: "AngerStyles", className: "AngerStyles" },
  { fontName: "Eavm", className: "Eavm" },
  { fontName: "CANAVAR", className: "Canavar" },
  { fontName: "Deltha", className: "Deltha" },
  { fontName: "Nasi", className: "Nasi" },
  { fontName: "airstrike", className: "airstrike" },
  { fontName: "Bring Race", className: "Bring-Race" },
  { fontName: "Masterpiece", className: "Masterpiece" },
  { fontName: "Game Of Squids", className: "Game-of-squids" },
  { fontName: "paladins", className: "Paladins" },
  { fontName: "NEXTSTEP", className: "Nextstep" },
  { fontName: "Chernobyl", className: "Chernobyl" },
  { fontName: "Metro", className: "Metro" },
  { fontName: "Molot", className: "Molot" },
  { fontName: "motherland", className: "Motherland" },
  { fontName: "Russian", className: "Russian" },
  { fontName: "Imperial", className: "Imperial" },
  { fontName: "propaganda", className: "Propaganda" },
  { fontName: "Soviet2", className: "Soviet2" },
  { fontName: "PROPAGAN", className: "Propagan" },
  { fontName: "Strengthen", className: "Strengthen" },
];

export default fontStyles;
